name: hackathon_venv
channels:
  - default
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - streamlit==1.39.0
    - pydantic
    - setuptools
    - python-dotenv
    - jupyter
    - pytest
    - pandas==2.2.3
    - openai==1.52.2
    - chromadb==0.5.15
    - langchain_community
    - langchain_text_splitters
    - pypdf
    - openpyxl
